setup_dir = "deepdetection_yocto"
release = "gatesgarth"
machine = "picozed-zynq7"

# Packages to be installed
packages = ["deepdetection-server"]

# Extra layer
#[[repo]]
#uri = "https://github.com/Xilinx/meta-xilinx-tools.git"
#layers = ["meta-xilinx-tools"]

# Needed for external flag
[srcs]
	[srcs.deepdetection-module]
	module = true
	path = "~/Develop/Work/DeepDetection/deepdetection_module"
	[srcs.linda-library]
	module = false
	path = "~/Develop/Work/linda/linda_library"
	[srcs.deepdetection-server]
	module = false
	path = "~/Develop/Work/DeepDetection/deepdetection_server"
