release = "zeus"
machine = "mercury-zx5"
packages = ["tar", "chrony", "ethtool", "net-tools", "tcpdump", "avahi-daemon", "gfa-server", "gfa-config", "mcp11aa02e48", "mtd-utils", "mtd-utils-jffs2", "iputils"]

# Extra layers
[[repo]]
uri = "git@gitlab.pic.es:DESI-GFA/meta-enclustra.git"
layers = ["meta-enclustra"]

[[repo]]
uri = "git@gitlab.pic.es:DESI-GFA/yocto/meta-gfa.git"
layers = ["meta-gfa"]

# Needed for external flag
[srcs]
	
	# After the dot goes the yocto package name for which
	# we want to use externalsrc
	[srcs.gfa-server]
	# If this source is of a module set this to true
	module = false
	path = "~/Develop/Work/DESI/gfaserver"
