setup_dir = "desi_yocto"
release = "zeus"
machine = "mercury-zx5"

# Extra layers
[[repo]]
uri = "git@gitlab.pic.es:DESI-GFA/meta-enclustra.git"
layers = ["meta-enclustra"]

[[repo]]
uri = "git@gitlab.pic.es:DESI-GFA/yocto/meta-gfa.git"
layers = ["meta-gfa"]
