release = "zeus"
machine = "mercury-zx5"

# Extra layers
[[layer]]
name = "meta-enclustra"
uri = "git@gitlab.pic.es:DESI-GFA/meta-enclustra.git"

[[layer]]
name = "meta-gfa"
uri = "git@gitlab.pic.es:DESI-GFA/yocto/meta-gfa.git"
