FROM debian:bullseye

RUN apt-get update 
RUN apt-get -y dist-upgrade

# Yocto and meta-xilinx dependencies
RUN apt-get install -y debianutils xterm git-core python3-git python3-pip python3-pexpect python3-jinja2 pylint3 python3 locales diffstat texinfo bzip2 gawk chrpath wget cpio make gcc-multilib g++ lsb-release procps libc-dev-bin lz4 zstd
RUN apt-get install -y sshpass
# Enclustra dependencies
RUN apt-get install -y curl bc libelf-dev libpcre3-dev
RUN git clone https://github.com/antmicro/zynq-mkbootimage; cd zynq-mkbootimage; make;  cp mkbootimage /usr/bin/

# Xilinx workarounds
RUN apt-get install -y screen

# Petalinux dependencies
RUN apt-get install -y autoconf zlib1g-dev libtinfo5 net-tools libncurses-dev libtool-bin xxd

# Qemu support
RUN apt-get update
RUN apt-get install -y sudo iptables

RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen; locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  
