FROM base-yocto

RUN echo 'build ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers

ARG uid
RUN id build 2>/dev/null || useradd --uid $uid --create-home build

ADD docker_ed25519 /home/build/.ssh/id_ed25519

RUN mkdir -p /home/build/.ssh; echo "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > /home/build/.ssh/config
RUN chown -R build:build /home/build/.ssh
RUN chmod 700 -R /home/build/.ssh

USER build
WORKDIR /home/build/gfayocto

CMD "/bin/bash" 
